const constant = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    INSERT_PRODUCT: 'INSERT_PRODUCT',
    REMOVE_PRODUCT: 'REMOVE_PRODUCT',
    CLEAR_PRODUCT: 'CLEAR_PRODUCT',
    SET_CART: 'SET_CART',
    REMOVE_CART: 'REMOVE_CART',
}

export default constant
